server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yourusername/config-repo.git
          clone-on-start: true
          search-paths: config-repo
